spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 3128351745@qq.com
    password: xroamekwcmmrdhcg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000