spring:
  #\u90AE\u4EF6
  mail:
    #\u53D1\u4EF6\u4EBA\u670D\u52A1\u5668
    host: smtp.qq.com
    port: 587
    #\u4E2A\u4EBA\u8D26\u6237\u548C\u5BC6\u7801
    username: 3128351745@qq.com
    password: xroamekwcmmrdhcg
    default-encoding: UTF-8
    #\u670D\u52A1\u5668\u8D85\u65F6\u914D\u7F6E
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000